# 构建设置
[build]
  publish = "/"
  command = ""  # 静态网站不需要构建命令

# 表单设置
[forms]
  [forms.order]
    name = "order"
    success_url = "/success.html"

# 重定向设置
[[redirects]]
  from = "/*"
  to = "/error.html"
  status = 404

# 头部设置
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self' https:; script-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' https://cdnjs.cloudflare.com https://fonts.googleapis.com; font-src 'self' https://cdnjs.cloudflare.com https://fonts.gstatic.com; img-src 'self' data:;"

# 环境变量设置
[context.production.environment]
  NODE_ENV = "production"

# 自定义404页面
[build.processing]
  skip_processing = false
[build.processing.html]
  pretty_urls = true 